# Flir Camera Config
#
# See flir_camera_driver/spinnaker_camera_driver/cfg/Spinnaker.cfg v0.2.5
# for parameter descriptions and default values

# Trigger parameters
enable_trigger: 'On'
trigger_selector: 'FrameStart'
trigger_activation_mode: 'RisingEdge'
trigger_source: 'Line0'
trigger_overlap_mode: 'ReadOut'
line_source: 'ExposureActive'
line_selector: 'Line1'
line_mode: 'Output'

# Image parameters
auto_white_balance: Continuous
image_format_color_coding: Mono8
isp_enable: false
