enable_trigger: 'On'
exposure_mode: 'Timed'
exposure_auto: 'Continuous'
# set higher until frame rate drops
auto_exposure_time_upper_limit: 24000
gamma_enable: false
line_mode: 'Output'
line_selector: 'Line1'
line_source: 'ExposureActive'
trigger_activation_mode: 'RisingEdge'
trigger_selector: 'FrameStart'
trigger_source: 'Line0'
trigger_overlap_mode: 'ReadOut'
timeout: 1000